base:
  config:
    mysql:
      hostname: mysql.lan
      port: 3306
      username: ossc
      password: ossc
    nacos:
      hostname: nacos.sca.oldtaoge.space
      port: 8848
    oauth2:
      hostname: localhost
      port: 8317

spring:
  application:
    name: BusinessCmsConfigService
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: nacos.sca.oldtaoge.space:8848
server:
  port: 9004

security:
  oauth2:
    client:
      client-id: client
      client-secret: 123456
      access-token-uri: http://${base.config.oauth2.hostname}:${base.config.oauth2.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth2.hostname}:${base.config.oauth2.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth2.hostname}:${base.config.oauth2.port}/oauth/check_token

dubbo:
  scan:
    base-packages: space.oldtaoge.ossc.server.business.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
